require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1
  TargetRailsVersion: 7.0
  Exclude:
    - bin/**/*
    - vendor/**/*
    - db/schema.rb
    - tmp/**/*
    - public/**/*


Rails:
  Enabled: true

Style/HashSyntax:
  Exclude:
      - ./**/*

Style/Documentation:
  Enabled: false

Metrics/CyclomaticComplexity:
  Exclude:
      - app/models/office.rb

Metrics/PerceivedComplexity:
  Exclude:
      - app/models/office.rb

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Max: 50

Metrics/BlockLength:
  Max: 50

Rails/BulkChangeTable:
  Enabled: false

RSpec/MultipleExpectations:
  Exclude:
      - spec/features/*
      - spec/models/*

RSpec/ContextWording:
  Enabled: false

RSpec/NestedGroups:
  Max: 4

RSpec/MultipleMemoizedHelpers:
  Max: 20

RSpec/ExampleLength:
  Exclude:
      - spec/features/*

RSpec/LetSetup:
  Exclude:
      - spec/features/*
      - spec/models/*
