'on':
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: rails
    services:
      db:
        image: mysql:8.0
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          TZ: 'Asia/Tokyo'
        ports:
          - 3306:3306
    env:
      RAILS_ENV: test
      TZ: 'Asia/Tokyo'
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v3

    # https://docs.github.com/en/enterprise-cloud@latest/actions/automating-builds-and-tests/building-and-testing-ruby
    - uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
        working-directory: rails

    # MySQLが立ち上がるまで待つために設定している
    - run: sleep 10

    - run: bundle exec rails db:create db:migrate
    - run: bundle exec rails tailwindcss:build dartsass:build
    - name: rspec
      run: bundle exec rspec
